version: "3.9"
services:
    app:
        image: webdevops/php-apache:8.3-alpine
        ports:
            - "4500:80"
        volumes:
            - ./www:/app

    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
        networks:
            - app-network

networks:
    app-network:
        driver: bridge